// <auto-generated />
using BookDataLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookDataLib.Migrations
{
    [DbContext(typeof(BookDataDbContext))]
    partial class BookDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookDataLib.Model.ArcStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterArcId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterArcId");

                    b.ToTable("ArcStages");
                });

            modelBuilder.Entity("BookDataLib.Model.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NovelId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PointOfViewId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.HasIndex("PointOfViewId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("BookDataLib.Model.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NovelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("BookDataLib.Model.CharacterArc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterArcs");
                });

            modelBuilder.Entity("BookDataLib.Model.Conflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Conflicts");
                });

            modelBuilder.Entity("BookDataLib.Model.Dialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SceneId");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("BookDataLib.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("ThreadId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BookDataLib.Model.FramingDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NovelId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("FramingDevices");
                });

            modelBuilder.Entity("BookDataLib.Model.Layer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NovelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("Layers");
                });

            modelBuilder.Entity("BookDataLib.Model.LayerScene", b =>
                {
                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("LayerId", "SceneId");

                    b.HasIndex("SceneId");

                    b.ToTable("LayerScenes");
                });

            modelBuilder.Entity("BookDataLib.Model.Motif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NovelId")
                        .HasColumnType("int");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Motifs");
                });

            modelBuilder.Entity("BookDataLib.Model.MotifScene", b =>
                {
                    b.Property<int>("MotifId")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("MotifId", "SceneId");

                    b.HasIndex("SceneId");

                    b.ToTable("MotifScenes");
                });

            modelBuilder.Entity("BookDataLib.Model.NarrativeStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NarrativeStructures");
                });

            modelBuilder.Entity("BookDataLib.Model.NarrativeThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.ToTable("NarrativeThreads");
                });

            modelBuilder.Entity("BookDataLib.Model.Novel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Novels");
                });

            modelBuilder.Entity("BookDataLib.Model.PacingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<double>("Tempo")
                        .HasColumnType("float");

                    b.Property<double>("TensionLevel")
                        .HasColumnType("float");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneId")
                        .IsUnique();

                    b.ToTable("PacingInfos");
                });

            modelBuilder.Entity("BookDataLib.Model.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NarrativeStructureId")
                        .HasColumnType("int");

                    b.Property<int>("NovelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NarrativeStructureId");

                    b.HasIndex("NovelId");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("BookDataLib.Model.PointOfView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NarratorDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PointsOfView");
                });

            modelBuilder.Entity("BookDataLib.Model.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SettingId");

                    b.HasIndex("ToneId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("BookDataLib.Model.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationHierarchy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BookDataLib.Model.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NovelId")
                        .HasColumnType("int");

                    b.Property<string>("VoiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("BookDataLib.Model.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NovelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("BookDataLib.Model.Tone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tones");
                });

            modelBuilder.Entity("BookDataLib.Model.ArcStage", b =>
                {
                    b.HasOne("BookDataLib.Model.CharacterArc", "CharacterArc")
                        .WithMany("ArcStages")
                        .HasForeignKey("CharacterArcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterArc");
                });

            modelBuilder.Entity("BookDataLib.Model.Chapter", b =>
                {
                    b.HasOne("BookDataLib.Model.Novel", "Novel")
                        .WithMany("Chapters")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.PointOfView", "PointOfView")
                        .WithMany("Chapters")
                        .HasForeignKey("PointOfViewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Novel");

                    b.Navigation("PointOfView");
                });

            modelBuilder.Entity("BookDataLib.Model.Character", b =>
                {
                    b.HasOne("BookDataLib.Model.Novel", null)
                        .WithMany("Characters")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BookDataLib.Model.CharacterArc", b =>
                {
                    b.HasOne("BookDataLib.Model.Character", "Character")
                        .WithMany("CharacterArcs")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("BookDataLib.Model.Conflict", b =>
                {
                    b.HasOne("BookDataLib.Model.Event", "Event")
                        .WithMany("Conflicts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BookDataLib.Model.Dialogue", b =>
                {
                    b.HasOne("BookDataLib.Model.Character", "Character")
                        .WithMany("Dialogues")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.Scene", "Scene")
                        .WithMany("Dialogues")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("BookDataLib.Model.Event", b =>
                {
                    b.HasOne("BookDataLib.Model.Scene", "Scene")
                        .WithMany("Events")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.NarrativeThread", "Thread")
                        .WithMany("Events")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("BookDataLib.Model.FramingDevice", b =>
                {
                    b.HasOne("BookDataLib.Model.Novel", "Novel")
                        .WithMany("FramingDevices")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("BookDataLib.Model.Layer", b =>
                {
                    b.HasOne("BookDataLib.Model.Novel", "Novel")
                        .WithMany("Layers")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("BookDataLib.Model.LayerScene", b =>
                {
                    b.HasOne("BookDataLib.Model.Layer", "Layer")
                        .WithMany("LayerScenes")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.Scene", "Scene")
                        .WithMany("LayerScenes")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Layer");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("BookDataLib.Model.Motif", b =>
                {
                    b.HasOne("BookDataLib.Model.Novel", "Novel")
                        .WithMany("Motifs")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.Theme", null)
                        .WithMany("Motifs")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("BookDataLib.Model.MotifScene", b =>
                {
                    b.HasOne("BookDataLib.Model.Motif", "Motif")
                        .WithMany("MotifScenes")
                        .HasForeignKey("MotifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.Scene", "Scene")
                        .WithMany("MotifScenes")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Motif");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("BookDataLib.Model.NarrativeThread", b =>
                {
                    b.HasOne("BookDataLib.Model.Plot", "Plot")
                        .WithMany("Threads")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("BookDataLib.Model.PacingInfo", b =>
                {
                    b.HasOne("BookDataLib.Model.Scene", "Scene")
                        .WithOne("PacingInfo")
                        .HasForeignKey("BookDataLib.Model.PacingInfo", "SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("BookDataLib.Model.Plot", b =>
                {
                    b.HasOne("BookDataLib.Model.NarrativeStructure", "NarrativeStructure")
                        .WithMany("Plots")
                        .HasForeignKey("NarrativeStructureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.Novel", "Novel")
                        .WithMany("Plots")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NarrativeStructure");

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("BookDataLib.Model.Scene", b =>
                {
                    b.HasOne("BookDataLib.Model.Chapter", "Chapter")
                        .WithMany("Scenes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.Setting", "Setting")
                        .WithMany("Scenes")
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDataLib.Model.Tone", "Tone")
                        .WithMany("Scenes")
                        .HasForeignKey("ToneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Setting");

                    b.Navigation("Tone");
                });

            modelBuilder.Entity("BookDataLib.Model.Style", b =>
                {
                    b.HasOne("BookDataLib.Model.Novel", "Novel")
                        .WithMany("Styles")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("BookDataLib.Model.Theme", b =>
                {
                    b.HasOne("BookDataLib.Model.Novel", "Novel")
                        .WithMany("Themes")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("BookDataLib.Model.Chapter", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("BookDataLib.Model.Character", b =>
                {
                    b.Navigation("CharacterArcs");

                    b.Navigation("Dialogues");
                });

            modelBuilder.Entity("BookDataLib.Model.CharacterArc", b =>
                {
                    b.Navigation("ArcStages");
                });

            modelBuilder.Entity("BookDataLib.Model.Event", b =>
                {
                    b.Navigation("Conflicts");
                });

            modelBuilder.Entity("BookDataLib.Model.Layer", b =>
                {
                    b.Navigation("LayerScenes");
                });

            modelBuilder.Entity("BookDataLib.Model.Motif", b =>
                {
                    b.Navigation("MotifScenes");
                });

            modelBuilder.Entity("BookDataLib.Model.NarrativeStructure", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("BookDataLib.Model.NarrativeThread", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BookDataLib.Model.Novel", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Characters");

                    b.Navigation("FramingDevices");

                    b.Navigation("Layers");

                    b.Navigation("Motifs");

                    b.Navigation("Plots");

                    b.Navigation("Styles");

                    b.Navigation("Themes");
                });

            modelBuilder.Entity("BookDataLib.Model.Plot", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("BookDataLib.Model.PointOfView", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("BookDataLib.Model.Scene", b =>
                {
                    b.Navigation("Dialogues");

                    b.Navigation("Events");

                    b.Navigation("LayerScenes");

                    b.Navigation("MotifScenes");

                    b.Navigation("PacingInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BookDataLib.Model.Setting", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("BookDataLib.Model.Theme", b =>
                {
                    b.Navigation("Motifs");
                });

            modelBuilder.Entity("BookDataLib.Model.Tone", b =>
                {
                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
